server:
  port: 8082
  servlet:
    session: 
      timeout: 60
# JSP 경로 설정
spring:
  main:
    allow-circular-references: true
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  datasource:
    url: jdbc:mysql://localhost:3306/sns?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
  mail:
    host: smtp.gmail.com
    port: 587
    username: photalk2@gmail.com #Gmail email
    password: qymxisfpnahvqyjw #Google 계정 2단계 인증 생성 후 앱 비밀번호 생성
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ac627f4f6cb3397b8fb6fe7a557c58df 
            client-secret: KQJCfQdnjfWjHCBH5bhPkmiTVzf1cx3n
            scope:
              - account_email
              - profile_nickname
              - gender
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8082/login/oauth2/code/kakao
            client-name: Kakao
            client-authentication-method: POST

          naver:
            client-id: 8k6tTgl_X5mXWraZ1X4k
            client-secret: kLBl4kvJts
            scope:
              - name
              - email
              - gender
              - mobile
              - nickname
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8082/login/oauth2/code/naver   

        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
        

mybatis:
  mapper-locations: classpath:mapper/*_mapper.xml
  configuration:
    map-underscore-to-camel-case: true
    call-setters-on-nulls: true
    jdbc-type-for-null: varchar

springdoc:
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
    operations-sorter: method

cloud:
  aws:
    region:
      static: ap-northeast-2
    s3:
      bucket: sns-file-upload
    credentials:
      access-key: AKIATNFYBYCSYJPDUGGN
      secret-key: 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
    stack:
      auto: false
